### PR TITLE
bump catalog to bundle ea7325b

### PR DESCRIPTION
**Pull request by jan--f**

### CODE REVIEW

**Comment by jan--f** [comment]
@lihongyan1 please merge if all builds are green for updated catalog images.

**Comment by danielmellado** [comment]
Seems that we're hitting capacity limit on s390x in the failing pipelines...

```
step-build

mkdir -p ~/.ssh
if [ -e "/ssh/error" ]; then
  #no server could be provisioned
  cat /ssh/error
  exit 1
fi
Error allocating host: timed out waiting for instance address

Context info:
  Platform: linux/s390x
  File:     /opt/app-root/src/pkg/reconciler/taskrun/taskrun.go
  Line:     455

```

**Pull request merged**
